project_name: ldc

run:
  deadline: 120s
  tests: false

linters:
  enable-all: true
  disable:
    - gochecknoinits
    - gochecknoglobals
    - gofmt
    - golint
    - lll
    - maligned
    - prealloc
    - unparam
  fast: false

linter-settings:
  goimports:
    local-prefixes: github.com/launchdarkly/ldc

issues:
  exclude:
    - "G104: Errors unhandled." # Let errcheck handle these
  exclude-use-default: false
  max-same-issues: 1000
  max-per-linter: 1000
