project_name: ldc

run:
  deadline: 120s
  tests: false

linters:
  enable-all: true
  disable:
    - gochecknoinits
    - gochecknoglobals
    - gofmt
    - golint
    - lll
    - maligned
    - prealloc
    - unparam
  fast: false

linter-settings:
  goimports:
    local-prefixes: github.com/launchdarkly/ldc

issues:
  exclude:
#    # golint exclusions
#    - "(const|func|method|struct field|type|var) .* should be " # golint errors about variable names (don't want to fix them because they're in a public interface)
    - "G104: Errors unhandled." # Let errcheck handle these
#    - "Error return value of `w.Write` is not checked"
#    - "should have comment or be unexported" # TODO: label everything that is exported when relay becomes a library
  exclude-use-default: false
  max-same-issues: 1000
  max-per-linter: 1000
