---
project_name: ldc

release:
  github:
    owner: launchdarkly
    name: ldc

builds:
  - binary: ldc
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - 386
    env:
      - CGO_ENABLED=0
    main: .
    ldflags: -s -w -X cmd.Version={{.Version}}

archive:
  format: tar.gz
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip
  name_template: '{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  files:
    - LICENSE.txt
    - README.md

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^dev:'
      - 'README'
      - Merge pull request
      - Merge branch

#brew:
#  github:
#    owner: launchdarkly
#    name: homebrew-tap
#  folder: Formula
#  homepage:  https://github.com/launchdarkly/ldc
#  description: LaunchDarkly CLI/Console tool
#  test: |
#    system "#{bin}/ldc version"
