/*
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * API version: 2.0.0
 * Contact: support@launchdarkly.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type FeatureFlag struct {

	Key string `json:"key,omitempty"`

	// Name of the feature flag.
	Name string `json:"name,omitempty"`

	// Whether the feature flag is a boolean flag or multivariate.
	Kind string `json:"kind,omitempty"`

	// A unix epoch time in milliseconds specifying the creation time of this flag.
	CreationDate float32 `json:"creationDate,omitempty"`

	IncludeInSnippet bool `json:"includeInSnippet,omitempty"`

	// Whether or not this flag is temporary.
	Temporary bool `json:"temporary,omitempty"`

	// The ID of the member that should maintain this flag.
	MaintainerId string `json:"maintainerId,omitempty"`

	// An array of tags for this feature flag.
	Tags []string `json:"tags,omitempty"`

	// The variations for this feature flag.
	Variations []Variation `json:"variations,omitempty"`

	Links *Links `json:"_links,omitempty"`

	Maintainer *Member `json:"_maintainer,omitempty"`

	Environments map[string]FeatureFlagConfig `json:"environments,omitempty"`
}
