/*
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * API version: 2.0.0
 * Contact: support@launchdarkly.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PatchComment struct {

	Comment string `json:"comment,omitempty"`

	Patch []FlagsprojectKeyfeatureFlagKeyPatch `json:"patch,omitempty"`
}
