/*
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * API version: 2.0.0
 * Contact: support@launchdarkly.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import "encoding/json"

type Variation struct {
	Name string `json:"name,omitempty"`

	Description string `json:"description,omitempty"`

	Value json.RawMessage `json:"value"`
}
