version: 2

experimental:
  notify:
    branches:
      only:
        - main

defaults:
  environment: &environment
    CIRCLE_TEST_REPORTS: /tmp/circle-reports
    CIRCLE_ARTIFACTS: /tmp/circle-artifacts
    COMMON_GO_PACKAGES: >
      github.com/jstemmer/go-junit-report
      github.com/kyoh86/richgo

  build_steps: &build_steps
    steps:
      - checkout
      - run:
          name: Set up bats
          command: |
            git clone https://github.com/sstephenson/bats.git ~/bats
            cd ~/bats
            sudo ./install.sh /usr/local
      - run: GO111MODULE=off go get -u $COMMON_GO_PACKAGES
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: go mod verify
      - run: sudo apt-get update && sudo apt-get install python-pip
      - run: sudo pip2 install pre-commit
      - run: pre-commit install
      - run: SKIP=go-unit-tests pre-commit run -a
      - run:
          name: Set up Code Climate test-reporter
          command: |
            curl -sS -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run tests
          command: |
            mkdir -p $CIRCLE_TEST_REPORTS
            mkdir -p $CIRCLE_ARTIFACTS
            trap "go-junit-report < $CIRCLE_ARTIFACTS/report.txt > $CIRCLE_TEST_REPORTS/junit.xml" EXIT
            if [ -z "$DISABLE_COVERAGE" ]; then
              go_cover_args="-covermode=atomic -coverpkg=./... -coverprofile /tmp/circle-artifacts/coverage.txt"
            fi
            go test -race $go_cover_args -v $(go list ./... | grep -v /vendor/) | tee >(richgo testfilter) > $CIRCLE_ARTIFACTS/report.txt
            if [[ -z "$DISABLE_COVERAGE" && -n "$CC_TEST_REPORTER_ID" ]]; then
              ./cc-test-reporter format-coverage $CIRCLE_ARTIFACTS/coverage.txt -t gocov --output $CIRCLE_ARTIFACTS/coverage.json
              ./cc-test-reporter upload-coverage --input $CIRCLE_ARTIFACTS/coverage.json
            fi
      - run:
          name: Run integration tests
          command: |
            make integration-test
      - run:
          name: Generate coverage report
          command: |
            if [ -z "$DISABLE_COVERAGE" ]; then
              mkdir -p $CIRCLE_ARTIFACTS
              go tool cover -html=$CIRCLE_ARTIFACTS/coverage.txt -o $CIRCLE_ARTIFACTS/coverage.html
            fi
          when: always
      - store_test_results:
          path: /tmp/circle-reports
      - store_artifacts:
          path: /tmp/circle-artifacts

jobs:
  go-test:
    docker:
      - &build_image
        image: cimg/go:1.18.9
        environment:
          <<: *environment

    <<: *build_steps

  test-publish:
    docker:
      - <<: *build_image

    working_directory: &working_dir /go/src/github.com/launchdarkly/ldc
    steps:
      - checkout
      - run: make release-snapshot
      - store_artifacts:
          path: dist/

  publish:
    docker:
      - <<: *build_image

    working_directory: *working_dir
    steps:
      - checkout
      - run: sudo mkdir /go && sudo chown -R $USER:$USER /go
      - run:
          name: Releasing and publishing
          command: |
            make publish
      - store_artifacts:
          path: dist/

workflows:
  version: 2
  test:
    jobs:
      - go-test:
          filters:
            tags:
              only: /.*/
      - test-publish:
          filters:
            tags:
              only: /.*/
      - publish:
          filters:
            tags:
              only: /v\d+\.\d+\.\d+(-.*)?/
            branches:
              ignore: /.*/
          requires:
            - go-test
            - test-publish
