/*
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * API version: 2.0.0
 * Contact: support@launchdarkly.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type CustomRole struct {

	Links *Links `json:"_links,omitempty"`

	// Name of the custom role.
	Name string `json:"name,omitempty"`

	Key *CustomRoleKeyOrId `json:"key,omitempty"`

	// Description of the custom role.
	Description string `json:"description,omitempty"`

	Id *Id `json:"_id,omitempty"`

	Policy []Policy `json:"policy,omitempty"`
}
