/*
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * API version: 2.0.0
 * Contact: support@launchdarkly.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Member struct {

	Links *Links `json:"_links,omitempty"`

	Id *Id `json:"_id,omitempty"`

	Role *Role `json:"role,omitempty"`

	Email string `json:"email,omitempty"`

	PendingInvite bool `json:"_pendingInvite,omitempty"`

	IsBeta bool `json:"isBeta,omitempty"`

	CustomRoles []Id `json:"customRoles,omitempty"`
}
