/*
 * LaunchDarkly REST API
 *
 * Build custom integrations with the LaunchDarkly REST API
 *
 * API version: 2.0.0
 * Contact: support@launchdarkly.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type NonOwnerRole string

// List of NonOwnerRole
const (
	WRITER NonOwnerRole = "writer"
	READER NonOwnerRole = "reader"
	ADMIN NonOwnerRole = "admin"
)
